CREATE TABLE IF NOT EXISTS time_records
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    task_id     BIGINT NOT NULL,
    description TEXT NOT NULL,
    start_time  TIMESTAMPTZ NOT NULL,
    end_time    TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_time_records_task
        FOREIGN KEY (task_id) REFERENCES tasks(id),

    CONSTRAINT chk_time_records_period
        CHECK (end_time >= start_time)
);

CREATE INDEX IF NOT EXISTS idx_time_records_employee_id
    ON time_records(employee_id);

CREATE INDEX IF NOT EXISTS idx_time_records_task_id
    ON time_records(task_id);

CREATE INDEX IF NOT EXISTS idx_time_records_employee_period
    ON time_records(employee_id, start_time, end_time);
CREATE UNIQUE INDEX IF NOT EXISTS uk_time_records_task_id
    ON time_records(task_id);
